
import { Language, Translations, Crop, User, Conversation, Plot } from './types';

export const CROP_OPTIONS = Object.values(Crop);

export const CURRENT_USER_ID = 'user-main';
export const AI_USER_ID = 'user-ai';

export const LANGUAGE_OPTIONS = [
    { code: Language.EN, name: 'English' },
    { code: Language.RW, name: 'Kinyarwanda' },
    { code: Language.FR, name: 'Français' },
    { code: Language.SW, name: 'Kiswahili' },
];

const generateToken = () => Math.random().toString(36).substring(2, 12);

export const INITIAL_USERS: Record<string, User> = {
    [CURRENT_USER_ID]: { id: CURRENT_USER_ID, name: 'You', role: 'You', avatarColor: 'bg-green-500', isOnline: true, status: "Farming is life! 🌱", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
    [AI_USER_ID]: { id: AI_USER_ID, name: 'AI Farming Assistant', role: 'AI Assistant', avatarColor: 'bg-teal-500', isOnline: true, status: "Here to help with your crops.", profileLinkToken: generateToken(), linkExpiry: 'never', isLinkActive: false, connectionRequests: [], rejectedUserIds: [] },
    'user-john': { id: 'user-john', name: 'John', role: 'Farmer', avatarColor: 'bg-blue-500', isOnline: true, status: "Getting ready for the maize season.", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [{fromUserId: 'user-sylvie', timestamp: new Date(Date.now() - 3600000).toISOString(), status: 'pending'}], rejectedUserIds: [] },
    'user-maria': { id: 'user-maria', name: 'Maria', role: 'Buyer', avatarColor: 'bg-purple-500', isOnline: false, status: "Looking for fresh produce.", profileLinkToken: generateToken(), linkExpiry: '24h', isLinkActive: true, connectionRequests: [], rejectedUserIds: ['user-peter'] },
    'user-peter': { id: 'user-peter', name: 'Peter', role: 'Farmer', avatarColor: 'bg-orange-500', isOnline: true, status: "Coffee farmer from the Western Province.", profileLinkToken: generateToken(), linkExpiry: 'never', isLinkActive: false, connectionRequests: [], rejectedUserIds: [] },
    'user-sylvie': { id: 'user-sylvie', name: 'Sylvie', role: 'Farmer', avatarColor: 'bg-pink-500', isOnline: false, status: "Specializing in beans and potatoes.", profileLinkToken: generateToken(), linkExpiry: '3d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
    'user-amani': { id: 'user-amani', name: 'Amani', role: 'Buyer', avatarColor: 'bg-indigo-500', isOnline: true, status: "Exporting coffee and tea.", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
};

export const INITIAL_PLOTS: Plot[] = [
    { id: 'plot-1', ownerId: 'user-john', name: "John's Main Field", coordinates: [-1.9444, 30.0619], crop: Crop.MAIZE, size: 2.5, farmingStage: 'Growing' },
    { id: 'plot-2', ownerId: 'user-peter', name: "Peter's Coffee Plot", coordinates: [-2.0000, 29.7500], crop: Crop.COFFEE, size: 5, farmingStage: 'Harvesting' },
    { id: 'plot-3', ownerId: 'user-sylvie', name: "Sylvie's Potato Garden", coordinates: [-1.9333, 29.8667], crop: Crop.POTATOES, size: 1, farmingStage: 'Planting' },
    { id: 'plot-4', ownerId: 'user-sylvie', name: "Bean Field", coordinates: [-1.9350, 29.8700], crop: Crop.BEANS, size: 1.5, farmingStage: 'Growing' },
    { id: 'plot-5', ownerId: 'user-john', name: "Secondary Plot", coordinates: [-1.9460, 30.0600], crop: Crop.BEANS, size: 0.8, farmingStage: 'Fallow' },
    { id: 'plot-6', ownerId: CURRENT_USER_ID, name: "My Vegetable Garden", coordinates: [-1.958, 30.104], crop: Crop.BEANS, size: 0.5, farmingStage: 'Growing' },
];


export const INITIAL_CONVERSATIONS: Conversation[] = [
    {
        id: 'convo-ai',
        type: 'dm',
        participants: [CURRENT_USER_ID, AI_USER_ID],
        messages: [
            { id: `msg-${Date.now() - 20000}`, senderId: AI_USER_ID, text: "Hello! I am your AI Farming Assistant. How can I help you today? You can ask me about planting schedules, pest control, or anything related to farming.", timestamp: new Date(Date.now() - 20000).toISOString() },
        ]
    },
    {
        id: 'convo-1',
        type: 'dm',
        participants: [CURRENT_USER_ID, 'user-john'],
        messages: [
            { id: `msg-${Date.now() - 10000}`, senderId: 'user-john', text: "Hey! Are you going to the cooperative meeting tomorrow?", timestamp: new Date(Date.now() - 10000).toISOString() },
            { id: `msg-${Date.now() - 5000}`, senderId: CURRENT_USER_ID, text: "Yes, I'll be there. See you then!", timestamp: new Date(Date.now() - 5000).toISOString() }
        ]
    },
    {
        id: 'convo-2',
        type: 'group',
        name: 'Farming Cooperative',
        participants: [CURRENT_USER_ID, 'user-john', 'user-maria', 'user-peter'],
        messages: [
             { id: `msg-${Date.now() - 15000}`, senderId: 'user-maria', text: "Just a reminder that the new shipment of fertilizers has arrived.", timestamp: new Date(Date.now() - 15000).toISOString() },
             { id: `msg-${Date.now() - 12000}`, senderId: 'user-peter', text: "Great news! Thanks for the update, Maria.", timestamp: new Date(Date.now() - 12000).toISOString() }
        ]
    },
     {
        id: 'convo-3',
        type: 'dm',
        participants: [CURRENT_USER_ID, 'user-maria'],
        messages: [
             { id: `msg-${Date.now() - 86400000}`, senderId: 'user-maria', text: "I'm interested in buying 50kg of your maize harvest. What's your best price?", timestamp: new Date(Date.now() - 86400000).toISOString() }
        ]
    }
];

export const translations: Record<Language, Translations> = {
    [Language.EN]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Language',
            dashboard: 'Dashboard',
            map: 'Smart Map',
            chat: 'Chats',
            settings: 'Settings',
        },
        dashboard: {
            title: 'Farmer\'s Dashboard',
        },
        farmingTips: {
            title: 'AI Farming Assistant',
            selectCrop: 'Select a crop to get personalized tips:',
            getTips: 'Get Farming Tips',
            generating: 'Generating tips, please wait...',
            tipIntro: 'Here are some AI-generated tips for growing',
            error: 'Sorry, an error occurred while fetching tips. Please try again.',
        },
        chat: {
            title: 'Chats',
            groupName: 'Farming Cooperative',
            participants: 'participants',
            inputPlaceholder: 'Type a message...',
            searchPlaceholder: 'Search or start new chat',
            newChat: 'New Chat',
            welcomeTitle: 'Ubuhinzi360 Chat',
            welcomeMessage: 'Select a conversation to start messaging, or create a new chat to connect with farmers and buyers.',
            typing: 'typing...',
            newChatTitle: 'Start a new chat',
            startChat: 'Start Chat',
            noUsers: 'No new users available to chat with.',
            chatStartedSystemMessage: 'You started a conversation with {0}.',
        },
        map: {
            title: 'Smart Agricultural Map',
            addPlot: 'Add New Plot',
            legend: 'Legend',
            satelliteView: 'Satellite',
            streetView: 'Streets',
            filterByCrop: 'Filter by Crop',
            filterByFarmer: 'Filter by Farmer',
            allCrops: 'All Crops',
            allFarmers: 'All Farmers',
            plotDetails: 'Plot Details',
            owner: 'Owner',
            crop: 'Crop',
            size: 'Size',
            hectares: 'ha',
            farmingStage: 'Farming Stage',
            generateQrCode: 'Generate QR Code',
            editDetails: 'Edit Details',
            addPlotTitle: 'Add a New Farm Plot',
            plotName: 'Plot Name',
            clickToPlace: 'Click on the map to place your plot.',
            savePlot: 'Save Plot',
            cancel: 'Cancel',
            qrCodeTitle: 'Plot QR Code',
            scanQrCode: 'Scan this code to view plot details.',
            yieldPrediction: 'AI Yield Prediction',
            getYieldPrediction: 'Predict Yield',
            predicting: 'Analyzing data...',
            predictedYield: 'Predicted Yield: {0} tons/ha',
            predictionError: 'Could not predict yield at this time.',
            getDirections: 'Get Directions',
            directionsTo: 'Directions to {0}',
            fetchingLocation: 'Getting your current location...',
            locationError: 'Could not get your location. Please enable location services in your browser.',
            generatingDirections: 'Generating AI-powered directions...',
            directionsError: 'Sorry, could not generate directions at this time.',
            yourLocation: 'Your Location',
            destination: 'Destination',
            openInGoogleMaps: 'Open in Google Maps',
            startLocation: 'Starting Location',
            startLocationPlaceholder: 'e.g., Kanyinya market, Kigali',
            startLocationRequiredError: 'Please enter a starting location.',
        },
        settings: {
            title: 'Settings',
            profile: 'Profile',
            profileDescription: 'Edit your name, photo, and status',
            shareProfile: 'Share Profile & Requests',
            shareProfileDescription: 'Manage your link and connections',
            pendingRequests: '{0} pending',
            blockedUsers: 'Blocked Users',
            blockedUsersDescription: 'Manage users you have blocked',
            theme: 'Appearance',
            themeDescription: 'Customize the look and feel',
            language: 'Language',
            languageDescription: 'Choose the app language',
            privacy: 'Privacy',
            privacyDescription: 'Control who can see your info',
            notifications: 'Notifications',
            notificationsDescription: 'Manage alerts and sounds',
            account: 'Account',
            accountDescription: 'Manage your account',
            help: 'Help & Support',
            helpDescription: 'Get help and report issues',
            editProfile: 'Edit Profile',
            editPhoto: 'Edit Photo',
            displayName: 'Display Name',
            status: 'Status',
            save: 'Save',
            saved: 'Saved!',
            unblock: 'Unblock',
            noBlockedUsers: "You haven't blocked anyone.",
            blockNewUser: 'Block a User',
            blockUser: 'Block',
            selectUserToBlock: 'Select a user to block',
            light: 'Light',
            dark: 'Dark',
            english: 'English',
            kinyarwanda: 'Kinyarwanda',
            whoCanContactMe: 'Who can contact me',
            whoCanSeeProfile: 'Who can see my profile photo',
            whoCanSeeStatus: 'Who can see my status',
            everyone: 'Everyone',
            contactsOnly: 'Contacts Only',
            nobody: 'Nobody',
            messageNotifications: 'Message Notifications',
            groupNotifications: 'Group Notifications',
            sound: 'Sound',
            vibration: 'Vibration',
            logout: 'Log Out',
            deleteAccount: 'Delete Account',
            deleteAccountConfirmationTitle: 'Are you sure?',
            deleteAccountConfirmationMessage: 'This action is irreversible. All your data will be permanently deleted.',
            cancel: 'Cancel',
            delete: 'Delete',
            faq: 'FAQs',
            contactSupport: 'Contact Support',
            reportProblem: 'Report a Problem',
            shareProfileTitle: 'Share Profile & Requests',
            myLink: 'My Link',
            requests: 'Requests',
            connect: 'Connect',
            yourProfileLink: 'Your Profile Link',
            copyLink: 'Copy Link',
            linkCopied: 'Link copied to clipboard!',
            showQrCode: 'Show QR Code',
            linkSettings: 'Link Settings',
            linkActive: 'Profile Link Active',
            linkActiveDescription: 'Allow others to send you connection requests via your link.',
            linkExpiry: 'Link Auto-Expiry',
            expiry24h: '24 Hours',
            expiry3d: '3 Days',
            expiry7d: '7 Days',
            expiryNever: 'Never',
            pending: 'Pending',
            history: 'History',
            noPendingRequests: 'No new connection requests.',
            accept: 'Accept',
            reject: 'Reject',
            accepted: 'Accepted',
            rejected: 'Rejected',
            connectWithUser: 'Connect with a User',
            pasteLink: 'Paste user\'s profile link here',
            sendRequest: 'Send Request',
            requestSent: 'Connection request sent!',
            invalidLink: 'Invalid or expired link.',
            cannotRequestSelf: 'You cannot send a request to yourself.',
            alreadyConnected: 'You are already connected with this user.',
            requestBlocked: 'This user is not accepting requests, or you have been blocked.',
            back: 'Back to Settings',
        },
    },
    [Language.RW]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Ururimi',
            dashboard: 'Imbonerahamwe',
            map: 'Ikarita y\'Ubuhinzi',
            chat: 'Ibiganiro',
            settings: 'Igenamiterere',
        },
        dashboard: {
            title: 'Imbonerahamwe y\'Umuhinzi',
        },
        farmingTips: {
            title: 'Umujyanama mu Buhinzi wa AI',
            selectCrop: 'Hitamo igihingwa kugirango ubone inama:',
            getTips: 'Saba Inama z\'Ubuhinzi',
            generating: 'Turimo gutunganya inama, nyamuneka tegereza...',
            tipIntro: 'Dore inama z\'ubwenge bwa mudasobwa zo guhinga',
            error: 'Tubiseguyeho, habaye ikibazo mu kubona inama. Nyamuneka ongera ugerageze.',
        },
        chat: {
            title: 'Ibiganiro',
            groupName: 'Koperative y\'Abahinzi',
            participants: 'abitabiriye',
            inputPlaceholder: 'Andika ubutumwa...',
            searchPlaceholder: 'Shakisha cyangwa tangira ikiganiro gishya',
            newChat: 'Ikiganiro Gishya',
            welcomeTitle: 'Ikiganiro cya Ubuhinzi360',
            welcomeMessage: 'Hitamo ikiganiro kugirango utangire kohereza ubutumwa, cyangwa ufungure ikiganiro gishya kugirango wihuze n\'abahinzi n\'abaguzi.',
            typing: 'arandika...',
            newChatTitle: 'Tangira ikiganiro gishya',
            startChat: 'Tangira Ikiganiro',
            noUsers: 'Nta bakoresha bashya babonetse bo kuganira na bo.',
            chatStartedSystemMessage: 'Watangiye ikiganiro na {0}.',
        },
        map: {
            title: 'Ikarita y\'Ubuhinzi Bugezweho',
            addPlot: 'Ongeraho Isambu Nshya',
            legend: 'Ubusobanuro',
            satelliteView: 'Satelite',
            streetView: 'Imbibi',
            filterByCrop: 'Yungurura ku Gihingwa',
            filterByFarmer: 'Yungurura ku Muhinzi',
            allCrops: 'Ibihingwa Byose',
            allFarmers: 'Abahinzi Bose',
            plotDetails: 'Amakuru y\'Isambu',
            owner: 'Nyirayo',
            crop: 'Igihingwa',
            size: 'Ingano',
            hectares: 'ha',
            farmingStage: 'Igihe cy\'Ihinga',
            generateQrCode: 'Kora Kode ya QR',
            editDetails: 'Hindura Amakuru',
            addPlotTitle: 'Ongeraho Isambu Nshya',
            plotName: 'Izina ry\'Isambu',
            clickToPlace: 'Kanda ku ikarita ushyireho isambu yawe.',
            savePlot: 'Bika Isambu',
            cancel: 'Rekura',
            qrCodeTitle: 'Kode ya QR y\'Isambu',
            scanQrCode: 'Sikana iyi kode urebe amakuru y\'isambu.',
            yieldPrediction: 'AI Iteganya Umusaruro',
            getYieldPrediction: 'Ganya Umusaruro',
            predicting: 'Isesengura ririmo gukorwa...',
            predictedYield: 'Umusaruro uteganijwe: Toni {0}/ha',
            predictionError: 'Kuganya umusaruro ntibishoboye ubu.',
            getDirections: 'Reba Inzira',
            directionsTo: 'Inzira igana kuri {0}',
            fetchingLocation: 'Turimo gushaka aho uherereye...',
            locationError: 'Ntibishoboye kubona aho uherereye. Nyamuneka fungura serivisi z\'aho uherereye.',
            generatingDirections: 'Turimo gutunganya inzira za AI...',
            directionsError: 'Tubiseguyeho, ntibishoboye gutanga inzira ubu.',
            yourLocation: 'Aho Uherereye',
            destination: 'Aho Ugiye',
            openInGoogleMaps: 'Fungura muri Google Maps',
            startLocation: 'Aho Uhagurukira',
            startLocationPlaceholder: 'Urugero: Isoko rya Kanyinya, Kigali',
            startLocationRequiredError: 'Nyamuneka shyiramo aho uhagurukira.',
        },
        settings: {
            title: 'Igenamiterere',
            profile: 'Umwirondoro',
            profileDescription: 'Hindura izina, ifoto, na status yawe',
            shareProfile: 'Sangiza Umwirondoro & Ibyifuzo',
            shareProfileDescription: 'Genzura umurongo wawe n\'abakwihuza',
            pendingRequests: '{0} bitegereje',
            blockedUsers: 'Abakoresha Bahagaritswe',
            blockedUsersDescription: 'Genzura abantu wahagaritse',
            theme: 'Imigaragarire',
            themeDescription: 'Hindura uko porogaramu igaragara',
            language: 'Ururimi',
            languageDescription: 'Hitamo ururimi rwa porogaramu',
            privacy: 'Ibihanga n\'uburenganzira',
            privacyDescription: 'Genzura ababona amakuru yawe',
            notifications: 'Imenyesha',
            notificationsDescription: 'Genzura ibimenyetso n\'amajwi',
            account: 'Konti',
            accountDescription: 'Genzura konti yawe',
            help: 'Ubufasha',
            helpDescription: 'Shaka ubufasha cyangwa utange ikibazo',
            editProfile: 'Hindura Umwirondoro',
            editPhoto: 'Hindura Ifoto',
            displayName: 'Izina Rigaragara',
            status: 'Uko umeze',
            save: 'Bika',
            saved: 'Byabitswe!',
            unblock: 'Fungura',
            noBlockedUsers: 'Nta muntu urahagarika.',
            blockNewUser: 'Hagarika umukoresha',
            blockUser: 'Hagarika',
            selectUserToBlock: 'Hitamo umukoresha wo guhagarika',
            light: 'Umucyo',
            dark: 'Umwijima',
            english: 'Icyongereza',
            kinyarwanda: 'Ikinyarwanda',
            whoCanContactMe: 'Ninde ushobora kukwandikira',
            whoCanSeeProfile: 'Ninde ushobora kubona ifoto yawe',
            whoCanSeeStatus: 'Ninde ushobora kubona uko umeze',
            everyone: 'Abantu bose',
            contactsOnly: 'Abantu banjye',
            nobody: 'Nta n\'umwe',
            messageNotifications: 'Imenyesha ry\'ubutumwa',
            groupNotifications: 'Imenyesha ry\'itsinda',
            sound: 'Ijwi',
            vibration: 'Guhinda',
            logout: 'Sohoka',
            deleteAccount: 'Siba Konti',
            deleteAccountConfirmationTitle: 'Urabikomeje?',
            deleteAccountConfirmationMessage: 'Iki gikorwa ntigisubirwaho. Amakuru yawe yose azasibwa burundu.',
            cancel: 'Rekura',
            delete: 'Siba',
            faq: 'Ibibazo Bikunze Kubazwa',
            contactSupport: 'Vugana n\'Ubufasha',
            reportProblem: 'Tanga Ikibazo',
            shareProfileTitle: 'Sangiza Umwirondoro & Ibyifuzo',
            myLink: 'Umurongo Wanjye',
            requests: 'Ibyifuzo',
            connect: 'Huza',
            yourProfileLink: 'Umurongo wawe w\'umwirondoro',
            copyLink: 'Koporora Umurongo',
            linkCopied: 'Umurongo wakoporowe!',
            showQrCode: 'Erekana Kode ya QR',
            linkSettings: 'Igenamiterere ry\'Umurongo',
            linkActive: 'Umurongo w\'umwirondoro urakora',
            linkActiveDescription: 'Emerera abandi kukohereza ibyifuzo byo guhuzwa bakoresheje umurongo wawe.',
            linkExpiry: 'Igihe Umurongo Uzamarira',
            expiry24h: 'Amasaha 24',
            expiry3d: 'Iminsi 3',
            expiry7d: 'Iminsi 7',
            expiryNever: 'Nta na rimwe',
            pending: 'Bitegereje',
            history: 'Amateka',
            noPendingRequests: 'Nta byifuzo bishya byo guhuzwa.',
            accept: 'Emera',
            reject: 'Hakana',
            accepted: 'Byemejwe',
            rejected: 'Byahakanywe',
            connectWithUser: 'Huza n\'Umukoresha',
            pasteLink: 'Shyiramo umurongo w\'umukoresha hano',
            sendRequest: 'Ohereza Icyifuzo',
            requestSent: 'Icyifuzo cyo guhuzwa cyoherejwe!',
            invalidLink: 'Umurongo udakora cyangwa wararangiye.',
            cannotRequestSelf: 'Ntushobora kwiyohereza icyifuzo.',
            alreadyConnected: 'Usanzwe uhujwe n\'uyu mukoresha.',
            requestBlocked: 'Uyu mukoresha ntiyakira ibyifuzo, cyangwa warahagaritswe.',
            back: 'Subira ku Igenamiterere',
        },
    },
    [Language.FR]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Langue',
            dashboard: 'Tableau de bord',
            map: 'Carte Intelligente',
            chat: 'Discussions',
            settings: 'Paramètres',
        },
        dashboard: {
            title: "Tableau de bord de l'agriculteur",
        },
        farmingTips: {
            title: 'Assistant Agricole IA',
            selectCrop: 'Sélectionnez une culture pour des conseils personnalisés:',
            getTips: 'Obtenir des conseils agricoles',
            generating: 'Génération de conseils, veuillez patienter...',
            tipIntro: "Voici quelques conseils générés par l'IA pour la culture de",
            error: "Désolé, une erreur s'est produite lors de la récupération des conseils. Veuillez réessayer.",
        },
        chat: {
            title: 'Discussions',
            groupName: 'Coopérative Agricole',
            participants: 'participants',
            inputPlaceholder: 'Écrire un message...',
            searchPlaceholder: 'Chercher ou démarrer une nouvelle discussion',
            newChat: 'Nouvelle discussion',
            welcomeTitle: 'Discussion Ubuhinzi360',
            welcomeMessage: "Sélectionnez une conversation pour commencer à discuter, ou créez une nouvelle discussion pour vous connecter avec des agriculteurs et des acheteurs.",
            typing: 'écrit...',
            newChatTitle: 'Démarrer une nouvelle discussion',
            startChat: 'Démarrer la discussion',
            noUsers: 'Aucun nouvel utilisateur disponible pour discuter.',
            chatStartedSystemMessage: 'Vous avez commencé une conversation avec {0}.',
        },
         map: {
            title: 'Carte Agricole Intelligente',
            addPlot: 'Ajouter une parcelle',
            legend: 'Légende',
            satelliteView: 'Satellite',
            streetView: 'Rues',
            filterByCrop: 'Filtrer par culture',
            filterByFarmer: 'Filtrer par agriculteur',
            allCrops: 'Toutes les cultures',
            allFarmers: 'Tous les agriculteurs',
            plotDetails: 'Détails de la parcelle',
            owner: 'Propriétaire',
            crop: 'Culture',
            size: 'Taille',
            hectares: 'ha',
            farmingStage: 'Stade de culture',
            generateQrCode: 'Générer un code QR',
            editDetails: 'Modifier les détails',
            addPlotTitle: 'Ajouter une nouvelle parcelle agricole',
            plotName: 'Nom de la parcelle',
            clickToPlace: 'Cliquez sur la carte pour placer votre parcelle.',
            savePlot: 'Enregistrer la parcelle',
            cancel: 'Annuler',
            qrCodeTitle: 'Code QR de la parcelle',
            scanQrCode: 'Scannez ce code pour voir les détails de la parcelle.',
            yieldPrediction: 'Prédiction de rendement IA',
            getYieldPrediction: 'Prédire le rendement',
            predicting: 'Analyse des données...',
            predictedYield: 'Rendement prévu : {0} tonnes/ha',
            predictionError: 'Impossible de prédire le rendement pour le moment.',
            getDirections: "Obtenir l'itinéraire",
            directionsTo: 'Itinéraire vers {0}',
            fetchingLocation: 'Obtention de votre position actuelle...',
            locationError: 'Impossible d\'obtenir votre position. Veuillez activer les services de localisation.',
            generatingDirections: 'Génération d\'itinéraires par IA...',
            directionsError: 'Désolé, impossible de générer un itinéraire pour le moment.',
            yourLocation: 'Votre Position',
            destination: 'Destination',
            openInGoogleMaps: 'Ouvrir dans Google Maps',
            startLocation: 'Lieu de départ',
            startLocationPlaceholder: 'Ex: Marché de Kanyinya, Kigali',
            startLocationRequiredError: 'Veuillez entrer un lieu de départ.',
        },
        settings: {
            title: 'Paramètres',
            profile: 'Profil',
            profileDescription: 'Modifier votre nom, photo, et statut',
            shareProfile: 'Partager le Profil & Demandes',
            shareProfileDescription: 'Gérer votre lien et vos connexions',
            pendingRequests: '{0} en attente',
            blockedUsers: 'Utilisateurs Bloqués',
            blockedUsersDescription: 'Gérer les utilisateurs que vous avez bloqués',
            theme: 'Apparence',
            themeDescription: "Personnaliser l'apparence",
            language: 'Langue',
            languageDescription: "Choisir la langue de l'application",
            privacy: 'Confidentialité',
            privacyDescription: 'Contrôler qui peut voir vos informations',
            notifications: 'Notifications',
            notificationsDescription: 'Gérer les alertes et les sons',
            account: 'Compte',
            accountDescription: 'Gérer votre compte',
            help: 'Aide & Support',
            helpDescription: "Obtenir de l'aide et signaler des problèmes",
            editProfile: 'Modifier le profil',
            editPhoto: 'Modifier la photo',
            displayName: "Nom d'affichage",
            status: 'Statut',
            save: 'Enregistrer',
            saved: 'Enregistré !',
            unblock: 'Débloquer',
            noBlockedUsers: "Vous n'avez bloqué personne.",
            blockNewUser: 'Bloquer un utilisateur',
            blockUser: 'Bloquer',
            selectUserToBlock: 'Sélectionner un utilisateur à bloquer',
            light: 'Clair',
            dark: 'Sombre',
            english: 'Anglais',
            kinyarwanda: 'Kinyarwanda',
            whoCanContactMe: 'Qui peut me contacter',
            whoCanSeeProfile: 'Qui peut voir ma photo de profil',
            whoCanSeeStatus: 'Qui peut voir mon statut',
            everyone: 'Tout le monde',
            contactsOnly: 'Contacts uniquement',
            nobody: 'Personne',
            messageNotifications: 'Notifications de message',
            groupNotifications: 'Notifications de groupe',
            sound: 'Son',
            vibration: 'Vibration',
            logout: 'Se déconnecter',
            deleteAccount: 'Supprimer le compte',
            deleteAccountConfirmationTitle: 'Êtes-vous sûr(e) ?',
            deleteAccountConfirmationMessage: 'Cette action est irréversible. Toutes vos données seront définitivement supprimées.',
            cancel: 'Annuler',
            delete: 'Supprimer',
            faq: 'FAQ',
            contactSupport: 'Contacter le support',
            reportProblem: 'Signaler un problème',
            shareProfileTitle: 'Partager le Profil & Demandes',
            myLink: 'Mon Lien',
            requests: 'Demandes',
            connect: 'Connecter',
            yourProfileLink: 'Votre lien de profil',
            copyLink: 'Copier le lien',
            linkCopied: 'Lien copié dans le presse-papiers !',
            showQrCode: 'Afficher le code QR',
            linkSettings: 'Paramètres du lien',
            linkActive: 'Lien de profil actif',
            linkActiveDescription: "Permettre aux autres de vous envoyer des demandes de connexion via votre lien.",
            linkExpiry: 'Expiration automatique du lien',
            expiry24h: '24 Heures',
            expiry3d: '3 Jours',
            expiry7d: '7 Jours',
            expiryNever: 'Jamais',
            pending: 'En attente',
            history: 'Historique',
            noPendingRequests: 'Aucune nouvelle demande de connexion.',
            accept: 'Accepter',
            reject: 'Rejeter',
            accepted: 'Acceptée',
            rejected: 'Rejetée',
            connectWithUser: 'Se connecter avec un utilisateur',
            pasteLink: "Collez le lien du profil de l'utilisateur ici",
            sendRequest: 'Envoyer la demande',
            requestSent: 'Demande de connexion envoyée !',
            invalidLink: 'Lien invalide ou expiré.',
            cannotRequestSelf: 'Vous ne pouvez pas vous envoyer une demande.',
            alreadyConnected: 'Vous êtes déjà connecté(e) avec cet utilisateur.',
            requestBlocked: "Cet utilisateur n'accepte pas les demandes, ou vous avez été bloqué(e).",
            back: 'Retour aux Paramètres',
        },
    },
    [Language.SW]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Lugha',
            dashboard: 'Dashibodi',
            map: 'Ramani Mahiri',
            chat: 'Soga',
            settings: 'Mipangilio',
        },
        dashboard: {
            title: 'Dashibodi ya Mkulima',
        },
        farmingTips: {
            title: 'Msaidizi wa Kilimo wa AI',
            selectCrop: 'Chagua zao kupata ushauri maalum:',
            getTips: 'Pata Ushauri wa Kilimo',
            generating: 'Inatayarisha ushauri, tafadhali subiri...',
            tipIntro: 'Hapa kuna ushauri uliotolewa na AI kwa ajili ya kulima',
            error: 'Samahani, kosa limetokea wakati wa kupata ushauri. Tafadhali jaribu tena.',
        },
        chat: {
            title: 'Soga',
            groupName: 'Ushirika wa Wakulima',
            participants: 'washiriki',
            inputPlaceholder: 'Andika ujumbe...',
            searchPlaceholder: 'Tafuta au anzisha soga mpya',
            newChat: 'Soga Mpya',
            welcomeTitle: 'Soga ya Ubuhinzi360',
            welcomeMessage: 'Chagua mazungumzo ili kuanza kutuma ujumbe, au unda soga mpya kuungana na wakulima na wanunuzi.',
            typing: 'anaandika...',
            newChatTitle: 'Anzisha soga mpya',
            startChat: 'Anza Soga',
            noUsers: 'Hakuna watumiaji wapya wa kuzungumza nao.',
            chatStartedSystemMessage: 'Umeanza mazungumzo na {0}.',
        },
        map: {
            title: 'Ramani Mahiri ya Kilimo',
            addPlot: 'Ongeza Shamba Jipya',
            legend: 'Ufunguo',
            satelliteView: 'Satelaiti',
            streetView: 'Mitaa',
            filterByCrop: 'Chuja kwa Zao',
            filterByFarmer: 'Chuja kwa Mkulima',
            allCrops: 'Mazao Yote',
            allFarmers: 'Wakulima Wote',
            plotDetails: 'Maelezo ya Shamba',
            owner: 'Mmiliki',
            crop: 'Zao',
            size: 'Ukubwa',
            hectares: 'ha',
            farmingStage: 'Hatua ya Ukulima',
            generateQrCode: 'Tengeneza Nambari ya QR',
            editDetails: 'Hariri Maelezo',
            addPlotTitle: 'Ongeza Shamba Jipya la Kilimo',
            plotName: 'Jina la Shamba',
            clickToPlace: 'Bofya kwenye ramani ili kuweka shamba lako.',
            savePlot: 'Hifadhi Shamba',
            cancel: 'Ghairi',
            qrCodeTitle: 'Nambari ya QR ya Shamba',
            scanQrCode: 'Changanua nambari hii ili kuona maelezo ya shamba.',
            yieldPrediction: 'Utabiri wa Mazao wa AI',
            getYieldPrediction: 'Tabiri Mazao',
            predicting: 'Inachambua data...',
            predictedYield: 'Mazao yaliyotabiriwa: tani {0}/ha',
            predictionError: 'Haikuweza kutabiri mazao kwa sasa.',
            getDirections: 'Pata Maelekezo',
            directionsTo: 'Maelekezo kwenda {0}',
            fetchingLocation: 'Inapata eneo lako la sasa...',
            locationError: 'Imeshindwa kupata eneo lako. Tafadhali wezesha huduma za eneo.',
            generatingDirections: 'Inatayarisha maelekezo ya AI...',
            directionsError: 'Samahani, haikuweza kutayarisha maelekezo kwa sasa.',
            yourLocation: 'Eneo Lako',
            destination: 'Unakoenda',
            openInGoogleMaps: 'Fungua katika Ramani za Google',
            startLocation: 'Eneo la Kuanzia',
            startLocationPlaceholder: 'Mfano: Soko la Kanyinya, Kigali',
            startLocationRequiredError: 'Tafadhali ingiza eneo la kuanzia.',
        },
        settings: {
            title: 'Mipangilio',
            profile: 'Wasifu',
            profileDescription: 'Hariri jina, picha, na hali yako',
            shareProfile: 'Shiriki Wasifu & Maombi',
            shareProfileDescription: 'Dhibiti kiungo chako na miunganisho',
            pendingRequests: '{0} zinasubiri',
            blockedUsers: 'Watumiaji Waliozuiwa',
            blockedUsersDescription: 'Dhibiti watumiaji uliowazuia',
            theme: 'Muonekano',
            themeDescription: 'Binafsisha mwonekano na hisia',
            language: 'Lugha',
            languageDescription: 'Chagua lugha ya programu',
            privacy: 'Faragha',
            privacyDescription: 'Dhibiti nani anayeweza kuona maelezo yako',
            notifications: 'Arifa',
            notificationsDescription: 'Dhibiti arifa na sauti',
            account: 'Akaunti',
            accountDescription: 'Dhibiti akaunti yako',
            help: 'Msaada & Usaidizi',
            helpDescription: 'Pata msaada na ripoti matatizo',
            editProfile: 'Hariri Wasifu',
            editPhoto: 'Hariri Picha',
            displayName: 'Jina la Kuonyesha',
            status: 'Hali',
            save: 'Hifadhi',
            saved: 'Imehifadhiwa!',
            unblock: 'Ondoa Kizuizi',
            noBlockedUsers: "Hujazuia mtu yeyote.",
            blockNewUser: 'Zuia Mtumiaji',
            blockUser: 'Zuia',
            selectUserToBlock: 'Chagua mtumiaji wa kumzuia',
            light: 'Mwangaza',
            dark: 'Giza',
            english: 'Kiingereza',
            kinyarwanda: 'Kinyarwanda',
            whoCanContactMe: 'Nani anaweza kuwasiliana nami',
            whoCanSeeProfile: 'Nani anaweza kuona picha yangu ya wasifu',
            whoCanSeeStatus: 'Nani anaweza kuona hali yangu',
            everyone: 'Kila mtu',
            contactsOnly: 'Anwani Zangu Pekee',
            nobody: 'Hakuna mtu',
            messageNotifications: 'Arifa za Ujumbe',
            groupNotifications: 'Arifa za Vikundi',
            sound: 'Sauti',
            vibration: 'Mtetemo',
            logout: 'Toka',
            deleteAccount: 'Futa Akaunti',
            deleteAccountConfirmationTitle: 'Una uhakika?',
            deleteAccountConfirmationMessage: 'Kitendo hiki hakiwezi kutenduliwa. Data yako yote itafutwa kabisa.',
            cancel: 'Ghairi',
            delete: 'Futa',
            faq: 'Maswali Yanayoulizwa Mara kwa Mara',
            contactSupport: 'Wasiliana na Usaidizi',
            reportProblem: 'Ripoti Tatizo',
            shareProfileTitle: 'Shiriki Wasifu & Maombi',
            myLink: 'Kiungo Changu',
            requests: 'Maombi',
            connect: 'Unganisha',
            yourProfileLink: 'Kiungo chako cha wasifu',
            copyLink: 'Nakili Kiungo',
            linkCopied: 'Kiungo kimenakiliwa kwenye ubao wa kunakili!',
            showQrCode: 'Onyesha Msimbo wa QR',
            linkSettings: 'Mipangilio ya Kiungo',
            linkActive: 'Kiungo cha Wasifu kinatumika',
            linkActiveDescription: 'Ruhusu wengine wakutumie maombi ya kuunganishwa kupitia kiungo chako.',
            linkExpiry: 'Muda wa Kuisha kwa Kiungo',
            expiry24h: 'Saa 24',
            expiry3d: 'Siku 3',
            expiry7d: 'Siku 7',
            expiryNever: 'Kamwe',
            pending: 'Inasubiri',
            history: 'Historia',
            noPendingRequests: 'Hakuna maombi mapya ya kuunganishwa.',
            accept: 'Kubali',
            reject: 'Kataa',
            accepted: 'Imekubaliwa',
            rejected: 'Imekataliwa',
            connectWithUser: 'Ungana na Mtumiaji',
            pasteLink: 'Bandika kiungo cha wasifu wa mtumiaji hapa',
            sendRequest: 'Tuma Ombi',
            requestSent: 'Ombi la kuunganishwa limetumwa!',
            invalidLink: 'Kiungo batili au muda wake umekwisha.',
            cannotRequestSelf: 'Huwezi kujitumia ombi.',
            alreadyConnected: 'Tayari umeunganishwa na mtumiaji huyu.',
            requestBlocked: 'Mtumiaji huyu hapokei maombi, au umezuiwa.',
            back: 'Rudi kwenye Mipangilio',
        },
    }
};