import { Language, Translations, Crop, User, Conversation } from './types';

export const CROP_OPTIONS = Object.values(Crop);

export const CURRENT_USER_ID = 'user-main';
export const AI_USER_ID = 'user-ai';

const generateToken = () => Math.random().toString(36).substring(2, 12);

export const INITIAL_USERS: Record<string, User> = {
    [CURRENT_USER_ID]: { id: CURRENT_USER_ID, name: 'You', role: 'You', avatarColor: 'bg-green-500', isOnline: true, status: "Farming is life! 🌱", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
    [AI_USER_ID]: { id: AI_USER_ID, name: 'AI Farming Assistant', role: 'AI Assistant', avatarColor: 'bg-teal-500', isOnline: true, status: "Here to help with your crops.", profileLinkToken: generateToken(), linkExpiry: 'never', isLinkActive: false, connectionRequests: [], rejectedUserIds: [] },
    'user-john': { id: 'user-john', name: 'John', role: 'Farmer', avatarColor: 'bg-blue-500', isOnline: true, status: "Getting ready for the maize season.", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [{fromUserId: 'user-sylvie', timestamp: new Date(Date.now() - 3600000).toISOString(), status: 'pending'}], rejectedUserIds: [] },
    'user-maria': { id: 'user-maria', name: 'Maria', role: 'Buyer', avatarColor: 'bg-purple-500', isOnline: false, status: "Looking for fresh produce.", profileLinkToken: generateToken(), linkExpiry: '24h', isLinkActive: true, connectionRequests: [], rejectedUserIds: ['user-peter'] },
    'user-peter': { id: 'user-peter', name: 'Peter', role: 'Farmer', avatarColor: 'bg-orange-500', isOnline: true, status: "Coffee farmer from the Western Province.", profileLinkToken: generateToken(), linkExpiry: 'never', isLinkActive: false, connectionRequests: [], rejectedUserIds: [] },
    'user-sylvie': { id: 'user-sylvie', name: 'Sylvie', role: 'Farmer', avatarColor: 'bg-pink-500', isOnline: false, status: "Specializing in beans and potatoes.", profileLinkToken: generateToken(), linkExpiry: '3d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
    'user-amani': { id: 'user-amani', name: 'Amani', role: 'Buyer', avatarColor: 'bg-indigo-500', isOnline: true, status: "Exporting coffee and tea.", profileLinkToken: generateToken(), linkExpiry: '7d', isLinkActive: true, connectionRequests: [], rejectedUserIds: [] },
};

export const INITIAL_CONVERSATIONS: Conversation[] = [
    {
        id: 'convo-ai',
        type: 'dm',
        participants: [CURRENT_USER_ID, AI_USER_ID],
        messages: [
            { id: `msg-${Date.now() - 20000}`, senderId: AI_USER_ID, text: "Hello! I am your AI Farming Assistant. How can I help you today? You can ask me about planting schedules, pest control, or anything related to farming.", timestamp: new Date(Date.now() - 20000).toISOString() },
        ]
    },
    {
        id: 'convo-1',
        type: 'dm',
        participants: [CURRENT_USER_ID, 'user-john'],
        messages: [
            { id: `msg-${Date.now() - 10000}`, senderId: 'user-john', text: "Hey! Are you going to the cooperative meeting tomorrow?", timestamp: new Date(Date.now() - 10000).toISOString() },
            { id: `msg-${Date.now() - 5000}`, senderId: CURRENT_USER_ID, text: "Yes, I'll be there. See you then!", timestamp: new Date(Date.now() - 5000).toISOString() }
        ]
    },
    {
        id: 'convo-2',
        type: 'group',
        name: 'Farming Cooperative',
        participants: [CURRENT_USER_ID, 'user-john', 'user-maria', 'user-peter'],
        messages: [
             { id: `msg-${Date.now() - 15000}`, senderId: 'user-maria', text: "Just a reminder that the new shipment of fertilizers has arrived.", timestamp: new Date(Date.now() - 15000).toISOString() },
             { id: `msg-${Date.now() - 12000}`, senderId: 'user-peter', text: "Great news! Thanks for the update, Maria.", timestamp: new Date(Date.now() - 12000).toISOString() }
        ]
    },
     {
        id: 'convo-3',
        type: 'dm',
        participants: [CURRENT_USER_ID, 'user-maria'],
        messages: [
             { id: `msg-${Date.now() - 86400000}`, senderId: 'user-maria', text: "I'm interested in buying 50kg of your maize harvest. What's your best price?", timestamp: new Date(Date.now() - 86400000).toISOString() }
        ]
    }
];

export const translations: Record<Language, Translations> = {
    [Language.EN]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Language',
            dashboard: 'Dashboard',
            chat: 'Chats',
            settings: 'Settings',
        },
        dashboard: {
            title: 'Farmer\'s Dashboard',
        },
        weather: {
            title: 'Weather in Kigali',
            location: 'Kigali, Rwanda',
            description: 'Partly Cloudy',
            humidity: 'Humidity',
            wind: 'Wind',
        },
        farmingTips: {
            title: 'AI Farming Assistant',
            selectCrop: 'Select a crop to get personalized tips:',
            getTips: 'Get Farming Tips',
            generating: 'Generating tips, please wait...',
            tipIntro: 'Here are some AI-generated tips for growing',
            error: 'Sorry, an error occurred while fetching tips. Please try again.',
        },
        chat: {
            title: 'Chats',
            groupName: 'Farming Cooperative',
            participants: 'participants',
            inputPlaceholder: 'Type a message...',
            searchPlaceholder: 'Search or start new chat',
            newChat: 'New Chat',
            welcomeTitle: 'Ubuhinzi360 Chat',
            welcomeMessage: 'Select a conversation to start messaging, or create a new chat to connect with farmers and buyers.',
            typing: 'typing...',
            newChatTitle: 'Start a new chat',
            startChat: 'Start Chat',
            noUsers: 'No new users available to chat with.',
            chatStartedSystemMessage: 'You started a conversation with {0}.',
        },
        settings: {
            title: 'Settings',
            profile: 'Profile',
            profileDescription: 'Edit your name, photo, and status',
            shareProfile: 'Share Profile & Requests',
            shareProfileDescription: 'Manage your link and connections',
            pendingRequests: '{0} pending',
            blockedUsers: 'Blocked Users',
            blockedUsersDescription: 'Manage users you have blocked',
            theme: 'Appearance',
            themeDescription: 'Customize the look and feel',
            language: 'Language',
            languageDescription: 'Choose the app language',
            privacy: 'Privacy',
            privacyDescription: 'Control who can see your info',
            notifications: 'Notifications',
            notificationsDescription: 'Manage alerts and sounds',
            account: 'Account',
            accountDescription: 'Manage your account',
            help: 'Help & Support',
            helpDescription: 'Get help and report issues',
            editProfile: 'Edit Profile',
            editPhoto: 'Edit Photo',
            displayName: 'Display Name',
            status: 'Status',
            save: 'Save',
            saved: 'Saved!',
            unblock: 'Unblock',
            noBlockedUsers: "You haven't blocked anyone.",
            blockNewUser: 'Block a User',
            blockUser: 'Block',
            selectUserToBlock: 'Select a user to block',
            light: 'Light',
            dark: 'Dark',
            english: 'English',
            kinyarwanda: 'Kinyarwanda',
            whoCanContactMe: 'Who can contact me',
            whoCanSeeProfile: 'Who can see my profile photo',
            whoCanSeeStatus: 'Who can see my status',
            everyone: 'Everyone',
            contactsOnly: 'Contacts Only',
            nobody: 'Nobody',
            messageNotifications: 'Message Notifications',
            groupNotifications: 'Group Notifications',
            sound: 'Sound',
            vibration: 'Vibration',
            logout: 'Log Out',
            deleteAccount: 'Delete Account',
            deleteAccountConfirmationTitle: 'Are you sure?',
            deleteAccountConfirmationMessage: 'This action is irreversible. All your data will be permanently deleted.',
            cancel: 'Cancel',
            delete: 'Delete',
            faq: 'FAQs',
            contactSupport: 'Contact Support',
            reportProblem: 'Report a Problem',
            shareProfileTitle: 'Share Profile & Requests',
            myLink: 'My Link',
            requests: 'Requests',
            connect: 'Connect',
            yourProfileLink: 'Your Profile Link',
            copyLink: 'Copy Link',
            linkCopied: 'Link copied to clipboard!',
            showQrCode: 'Show QR Code',
            linkSettings: 'Link Settings',
            linkActive: 'Profile Link Active',
            linkActiveDescription: 'Allow others to send you connection requests via your link.',
            linkExpiry: 'Link Auto-Expiry',
            expiry24h: '24 Hours',
            expiry3d: '3 Days',
            expiry7d: '7 Days',
            expiryNever: 'Never',
            pending: 'Pending',
            history: 'History',
            noPendingRequests: 'No new connection requests.',
            accept: 'Accept',
            reject: 'Reject',
            accepted: 'Accepted',
            rejected: 'Rejected',
            connectWithUser: 'Connect with a User',
            pasteLink: 'Paste user\'s profile link here',
            sendRequest: 'Send Request',
            requestSent: 'Connection request sent!',
            invalidLink: 'Invalid or expired link.',
            cannotRequestSelf: 'You cannot send a request to yourself.',
            alreadyConnected: 'You are already connected with this user.',
            requestBlocked: 'This user is not accepting requests, or you have been blocked.',
            back: 'Back to Settings',
        },
    },
    [Language.RW]: {
        header: {
            title: 'Ubuhinzi360',
            language: 'Ururimi',
            dashboard: 'Imbonerahamwe',
            chat: 'Ibiganiro',
            settings: 'Igenamiterere',
        },
        dashboard: {
            title: 'Imbonerahamwe y\'Umuhinzi',
        },
        weather: {
            title: 'Iteganyagihe i Kigali',
            location: 'Kigali, u Rwanda',
            description: 'Igice cy\'ibicu',
            humidity: 'Ubuhehere',
            wind: 'Umuyaga',
        },
        farmingTips: {
            title: 'Umujyanama mu Buhinzi wa AI',
            selectCrop: 'Hitamo igihingwa kugirango ubone inama:',
            getTips: 'Saba Inama z\'Ubuhinzi',
            generating: 'Turimo gutunganya inama, nyamuneka tegereza...',
            tipIntro: 'Dore inama z\'ubwenge bwa mudasobwa zo guhinga',
            error: 'Tubiseguyeho, habaye ikibazo mu kubona inama. Nyamuneka ongera ugerageze.',
        },
        chat: {
            title: 'Ibiganiro',
            groupName: 'Koperative y\'Abahinzi',
            participants: 'abitabiriye',
            inputPlaceholder: 'Andika ubutumwa...',
            searchPlaceholder: 'Shakisha cyangwa tangira ikiganiro gishya',
            newChat: 'Ikiganiro Gishya',
            welcomeTitle: 'Ikiganiro cya Ubuhinzi360',
            welcomeMessage: 'Hitamo ikiganiro kugirango utangire kohereza ubutumwa, cyangwa ufungure ikiganiro gishya kugirango wihuze n\'abahinzi n\'abaguzi.',
            typing: 'arandika...',
            newChatTitle: 'Tangira ikiganiro gishya',
            startChat: 'Tangira Ikiganiro',
            noUsers: 'Nta bakoresha bashya babonetse bo kuganira na bo.',
            chatStartedSystemMessage: 'Watangiye ikiganiro na {0}.',
        },
        settings: {
            title: 'Igenamiterere',
            profile: 'Umwirondoro',
            profileDescription: 'Hindura izina, ifoto, na status yawe',
            shareProfile: 'Sangiza Umwirondoro & Ibyifuzo',
            shareProfileDescription: 'Genzura umurongo wawe n\'abakwihuza',
            pendingRequests: '{0} bitegereje',
            blockedUsers: 'Abakoresha Bahagaritswe',
            blockedUsersDescription: 'Genzura abantu wahagaritse',
            theme: 'Imigaragarire',
            themeDescription: 'Hindura uko porogaramu igaragara',
            language: 'Ururimi',
            languageDescription: 'Hitamo ururimi rwa porogaramu',
            privacy: 'Ibihanga n\'uburenganzira',
            privacyDescription: 'Genzura ababona amakuru yawe',
            notifications: 'Imenyesha',
            notificationsDescription: 'Genzura ibimenyetso n\'amajwi',
            account: 'Konti',
            accountDescription: 'Genzura konti yawe',
            help: 'Ubufasha',
            helpDescription: 'Shaka ubufasha cyangwa utange ikibazo',
            editProfile: 'Hindura Umwirondoro',
            editPhoto: 'Hindura Ifoto',
            displayName: 'Izina Rigaragara',
            status: 'Uko umeze',
            save: 'Bika',
            saved: 'Byabitswe!',
            unblock: 'Fungura',
            noBlockedUsers: 'Nta muntu urahagarika.',
            blockNewUser: 'Hagarika umukoresha',
            blockUser: 'Hagarika',
            selectUserToBlock: 'Hitamo umukoresha wo guhagarika',
            light: 'Umucyo',
            dark: 'Umwijima',
            english: 'Icyongereza',
            kinyarwanda: 'Ikinyarwanda',
            whoCanContactMe: 'Ninde ushobora kukwandikira',
            whoCanSeeProfile: 'Ninde ushobora kubona ifoto yawe',
            whoCanSeeStatus: 'Ninde ushobora kubona uko umeze',
            everyone: 'Abantu bose',
            contactsOnly: 'Abantu banjye',
            nobody: 'Nta n\'umwe',
            messageNotifications: 'Imenyesha ry\'ubutumwa',
            groupNotifications: 'Imenyesha ry\'itsinda',
            sound: 'Ijwi',
            vibration: 'Guhinda',
            logout: 'Sohoka',
            deleteAccount: 'Siba Konti',
            deleteAccountConfirmationTitle: 'Urabikomeje?',
            deleteAccountConfirmationMessage: 'Iki gikorwa ntigisubirwaho. Amakuru yawe yose azasibwa burundu.',
            cancel: 'Rekura',
            delete: 'Siba',
            faq: 'Ibibazo Bikunze Kubazwa',
            contactSupport: 'Vugana n\'Ubufasha',
            reportProblem: 'Tanga Ikibazo',
            shareProfileTitle: 'Sangiza Umwirondoro & Ibyifuzo',
            myLink: 'Umurongo Wanjye',
            requests: 'Ibyifuzo',
            connect: 'Huza',
            yourProfileLink: 'Umurongo wawe w\'umwirondoro',
            copyLink: 'Koporora Umurongo',
            linkCopied: 'Umurongo wakoporowe!',
            showQrCode: 'Erekana Kode ya QR',
            linkSettings: 'Igenamiterere ry\'Umurongo',
            linkActive: 'Umurongo w\'umwirondoro urakora',
            linkActiveDescription: 'Emerera abandi kukohereza ibyifuzo byo guhuzwa bakoresheje umurongo wawe.',
            linkExpiry: 'Igihe Umurongo Uzamarira',
            expiry24h: 'Amasaha 24',
            expiry3d: 'Iminsi 3',
            expiry7d: 'Iminsi 7',
            expiryNever: 'Nta na rimwe',
            pending: 'Bitegereje',
            history: 'Amateka',
            noPendingRequests: 'Nta byifuzo bishya byo guhuzwa.',
            accept: 'Emera',
            reject: 'Hakana',
            accepted: 'Byemejwe',
            rejected: 'Byahakanywe',
            connectWithUser: 'Huza n\'Umukoresha',
            pasteLink: 'Shyiramo umurongo w\'umukoresha hano',
            sendRequest: 'Ohereza Icyifuzo',
            requestSent: 'Icyifuzo cyo guhuzwa cyoherejwe!',
            invalidLink: 'Umurongo udakora cyangwa wararangiye.',
            cannotRequestSelf: 'Ntushobora kwiyohereza icyifuzo.',
            alreadyConnected: 'Usanzwe uhujwe n\'uyu mukoresha.',
            requestBlocked: 'Uyu mukoresha ntiyakira ibyifuzo, cyangwa warahagaritswe.',
            back: 'Subira ku Igenamiterere',
        },
    }
};